<?php
	include('_blocks/_head.php');
	include('_blocks/_nav.php');
	include('_views/_slider.php');
	include('_views/_pink-factory.php');
	include('_views/_great-pink-muffin.php');
	include('_views/_product.php');
	include('_views/_contact.php');
	include('_blocks/_footer.php');
 ?>